INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (1, 'Francisco', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (2, 'Albert', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (3, 'Claudio', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (4, 'Gabriel', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (5, 'Hugo', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (6, 'Jaime', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (7, 'Jorge', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (8, 'Pedro', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (9, 'Ruben', NOW());
INSERT INTO USERS (ID, NAME, REGISTER_TIME) VALUES (10, 'Tulio', NOW());



INSERT INTO ROL (ID) VALUES ('ROL_A');
INSERT INTO ROL (ID) VALUES ('ROL_B');
INSERT INTO ROL (ID) VALUES ('ROL_C');


INSERT INTO USERS_ROLES (usuario_id,roles_id) VALUES (10,'ROL_C');
INSERT INTO USERS_ROLES (usuario_id,roles_id) VALUES (6,'ROL_C');
INSERT INTO USERS_ROLES (usuario_id,roles_id) VALUES (2,'ROL_C');
INSERT INTO USERS_ROLES (usuario_id,roles_id) VALUES (9,'ROL_A');

